### ISSUE TITLE
bad max_age value -> cookie deleted by Chrome

### ISSUE THREAD

**Issue by jderusse** [ailabs/django-auth-remember#4]
Because the max_age is a date instead of a number of seconds, the browser Chrome don't take care of the expires_date and delete the cookie.

my fix : 
in auth_remember/utils.py:50

max_age = COOKIE_AGE

**Comment by dhaaker** [comment]
Looks like we can drop the max_age altogether, it is auto-calculated if expires is an instance of datetime.datetime.

**Comment by mvantellingen** [comment]
Thanks, just released 0.3 with the fix and better packaging
